KEYCLOAK-15955 Implement a pluggable Upgrade strategy
keycloak/keycloak-operator pull request #262
Opened 2020-11-02 16:19 UTC by vmuzikar

## JIRA ID
KEYCLOAK-15955

## Additional Information

## Checklist:
- [X] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

## Additional Notes 
I'll add the docs once I've got the confirmation this is the right approach. ;)

2020-11-02 16:25 UTC, vmuzikar commented
@slaskawi I was not able to run `make code/gen`. It was failing on:
```
operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [keycloak:[v1alpha1], ] 
F1102 17:22:17.672959   12469 deepcopy.go:813] Hit an unsupported type invalid type for []invalid type
make: *** [code/gen] Error 255
```
It's apparently caused by `operator-sdk generate k8s` and it's happening for me on master too, so I assumed it's not caused by my changes.

However, I was able to run the rest of the commands from that make target, so hopefully the CRD is updated correctly.

2020-11-03 10:56 UTC, slaskawi commented
@vmuzikar The CRD generation works fine on my laptop:

```
$ make code/gen
operator-sdk generate k8s
INFO[0000] Running deepcopy code-generation for Custom Resource group versions: [keycloak:[v1alpha1], ] 
INFO[0008] Code-generation complete.                    
operator-sdk generate crds --crd-version v1beta1
INFO[0000] Running CRD generator.                       
INFO[0000] CRD generation complete.                     
# This is a copy-paste part of `operator-sdk generate openapi` command (suggested by the manual)
which ./bin/openapi-gen > /dev/null || go build -o ./bin/openapi-gen k8s.io/kube-openapi/cmd/openapi-gen
./bin/openapi-gen --logtostderr=true -o "" -i ./pkg/apis/keycloak/v1alpha1 -O zz_generated.openapi -p ./pkg/apis/keycloak/v1alpha1 -h ./hack/boilerplate.go.txt -r "-"
API rule violation: list_type_missing,github.com/keycloak/keycloak-operator/pkg/apis/keycloak/v1alpha1,KeycloakRealmSpec,RealmOverrides

$ operator-sdk version  
operator-sdk version: "v0.18.2", commit: "f059b5e17447b0bbcef50846859519340c17ffad", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"
```

2020-11-03 11:01 UTC, slaskawi requested changes
The code looks nice, but needs some changes:
- Please make sure Operator SDK works on your box. You may either build it from source or use a Fedora Docker Container. You may also find my email on our team's mailing list on a Docker container with prod utils.
- Please fix linter errors.
- You might simplify the code a bit.

2020-11-03 14:00 UTC, vmuzikar commented on pkg/controller/keycloak/keycloak_migrations.go
> +		// status into the desired state.
What the JIRA should be about? :) I mean it works, so it's not a bug. So, should it be a refactor task? Won't this migrator be deprecated soon anyway?

2020-11-03 15:04 UTC, vmuzikar commented on pkg/controller/keycloak/keycloak_migrations.go
> +	if cr.Spec.Migration.MigrationStrategy == v1alpha1.NoStrategy {
Done.

2020-11-03 15:05 UTC, vmuzikar commented on pkg/controller/keycloak/keycloak_migrations_test.go
> +	AssertReplicasCount(t, migratedActions, 5)
Done.

2020-11-03 15:19 UTC, vmuzikar commented
@slaskawi Thanks for your review! I've pushed the requested changes. Didn't squash them yet so it's more easily apparent.

> The code looks nice, but needs some changes:
> 
> * Please make sure Operator SDK works on your box. You may either build it from source or use a Fedora Docker Container. You may also find my email on our team's mailing list on a Docker container with prod utils.

The Operator SDK seem to be working for me, it's just `generate k8s` doesn't. I'll investigate more why is it so but I think re-generating k8s is not required for this PR, correct?
> * Please fix linter errors.

Done.
> * You might simplify the code a bit.

Done.

2020-11-03 15:47 UTC, vmuzikar commented
Fixed the `generate k8s`. I didn't have `GOROOT` set which was not a problem ... until now. https://github.com/operator-framework/operator-sdk/issues/1854#issuecomment-613202510 saved me. :)

2020-11-05 08:34 UTC, slaskawi commented on pkg/controller/keycloak/keycloak_migrations.go
> +		// status into the desired state.
oooh yeah.. sorry I misread this.

2020-11-05 08:34 UTC, slaskawi submitted a review, later dismissed
The code looks fine. Could you please squash everything into a single commit?

2020-11-05 09:05 UTC, vmuzikar commented
@slaskawi Ok, squashed.

Do we need to update the docs? Do we even have docs for the operator? :D Couldn't find any.

2020-11-09 13:48 UTC, jeesmon commented
@vmuzikar Operator documentation seems to be from here: https://github.com/keycloak/keycloak-documentation/tree/master/server_installation/topics/operator

2020-11-11 10:48 UTC, slaskawi commented
Dear contributor,

I'm putting this Pull Request on hold until we get our CI back (see https://github.com/keycloak/keycloak-operator/pull/266). Once the Github Actions Pull Request is merged, I will kindly ask you for rebasing your changes. Then, we'll proceed with a normal code review process.

Please see [this Keycloak DEV thread](https://groups.google.com/g/keycloak-dev/c/ijI9grpRw74) to learn more why we are migrating to Github Actions.

Sorry for inconvenience

2020-11-12 13:24 UTC, slaskawi commented
@vmuzikar Could you please rebase this?

2020-11-16 07:51 UTC, slaskawi commented
@vmuzikar Can I ask you to rebase this?

2020-11-20 10:31 UTC, vmuzikar commented
> @vmuzikar Can I ask you to rebase this?

Done.

Working on the docs now.

2020-11-20 16:24 UTC, vmuzikar commented
Docs PR: https://github.com/keycloak/keycloak-documentation/pull/1062

2020-11-23 07:06 UTC, slaskawi approved these changes

2020-11-23 07:06 UTC, merged

2020-11-23 07:07 UTC, slaskawi commented
Integrated, thanks @vmuzikar !

2020-11-23 07:09 UTC, slaskawi commented
@vmuzikar Could you also create a backport?