:bug: Use a init container to set PVC permissions
keycloak/keycloak-operator pull request #297
Opened 2020-12-28 10:32 UTC by Yannig

Launch a init container to fix permissions on PVC.
Fix a problem when launching a Keycloak instance with aws-ebs disk

## JIRA ID

No Jira ID

## Additional Information

I'm using the Keycloak operator with a Kops cluster deployed in AWS. When I try to deploy a Keycloak instance, the Postgresql instance fail to start with a problem on disk default owner (root).

The only way to fix the problem is to mount this persistent volume, set the owner to postgres (group postgres) and let the postgres container start.

## Verification Steps

- Create a Kops cluster with aws-ebs storage class
- Launch the operator
- Generate a Keycloak instance
- After a few seconds/minutes the Keycloak postgres must be started

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2021-01-11 08:43 UTC, slaskawi commented
This probably solves https://issues.redhat.com/browse/KEYCLOAK-14948 too.

2021-01-11 08:46 UTC, slaskawi requested changes
Thanks for the contribution, @Yannig !

Could you please change the commit message and get rid of the emoji? Folks are using many different tools for developments and I'm not sure it will render correctly in all of them. Otherwise, LGTM!

2021-01-11 21:32 UTC, Yannig commented
Sure, no problem :)

2021-01-12 07:51 UTC, slaskawi approved these changes

2021-01-12 07:51 UTC, merged

2021-01-12 07:52 UTC, slaskawi commented
Integrated, thanks @Yannig !