Check route readiness only if ExternalAccess is enabled
keycloak/keycloak-operator pull request #301
Opened 2021-01-07 16:31 UTC by matskiv

## Additional Information
*What:*
On OpenShift, Keycloak CR will be stuck with `status.ready = false` if `.spec.ExternalAccess.enable = false`

*Why:*
Keycloak Operator should not be waiting for the route to become ready if the route is disabled via Keycloak CR spec.

## Verification Steps
1. Install the operator on a testing Openshift cluster (or run it locally against a namespace on Openshift cluster)
2. Create a valid Keycloak CR with `.spec.ExternalAccess.enable = false`
3. After StatefulSet and Postgresql deployment become ready, `.status.ready` field of the CR should become `true` 

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2021-01-11 08:36 UTC, slaskawi requested changes
Could you add a test for this case? It might be a unit test. I just want to make sure we won't break it again.

2021-01-11 11:54 UTC, matskiv commented
@slaskawi good idea. Test added.

2021-01-12 07:32 UTC, slaskawi approved these changes

2021-01-12 07:33 UTC, merged

2021-01-12 07:33 UTC, slaskawi commented
Integrated, thanks @matskiv !