MGDAPI-1043
keycloak/keycloak-operator pull request #302
Opened 2021-01-11 15:02 UTC by CathalOConnorRH

## JIRA ID
Jira: https://issues.redhat.com/browse/MGDAPI-1043

## Additional Information
Remove dependency to k8sutil package.
We are upgrading to operator sdk >= 1.x and k8sutils is no longer exposed in these versions. 
I've ran e2e tests against a cluster and everything passed but open to other tests as required. 

## Verification Steps
Build and deploy from this branch to confirm installation and reconciliation works as expected. 

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2021-01-12 08:25 UTC, slaskawi requested changes
Thanks for the contribution @CathalOConnorRH 

A slightly better idea is to modify the `main.go` file in such a way, that `k8sutil` is not needed at all. May I ask you to introduce such changes?

2021-01-12 14:10 UTC, CathalOConnorRH commented
@slaskawi  I've pushed some new changes. Let me know what you think . Thanks

2021-01-14 11:27 UTC, slaskawi commented
@CathalOConnorRH Ouch! I didn't expect the changes to look that bad. I'm terribly sorry but it seems copy-pasting that file was the right decision and I suggested you to do the wrong thing.

May I kindly you to revert this back into the previous state (with the copy of the `k8sutil` file)? You can easily find the previous version in your local git by invoking `git reflog`. Again, I'm terribly sorry for changing my mind here but embedding the changes looks just terrible.

2021-01-14 14:06 UTC, CathalOConnorRH commented
> @CathalOConnorRH Ouch! I didn't expect the changes to look that bad. I'm terribly sorry but it seems copy-pasting that file was the right decision and I suggested you to do the wrong thing.
> 
> May I kindly you to revert this back into the previous state (with the copy of the `k8sutil` file)? You can easily find the previous version in your local git by invoking `git reflog`. Again, I'm terribly sorry for changing my mind here but embedding the changes looks just terrible.

@slaskawi No worries. I've reverted those changes now.

2021-01-15 09:08 UTC, slaskawi approved these changes

2021-01-15 09:08 UTC, merged

2021-01-15 09:09 UTC, slaskawi commented
Integrated, thanks @CathalOConnorRH