Allow Password policy to be defined in the keycloak realm CRD
keycloak/keycloak-operator pull request #337
Opened 2021-03-28 10:47 UTC by masoodfaisal

## https://issues.redhat.com/browse/KEYCLOAK-17607

## Additional Information
Setting up a password policy for realms in KeyCLoak is a frequent requirement by the customers. This change allows the realm yaml to specify the password policy for the realm

## Verification Steps
Run the local setup make code/run
DEfine password policy as per deploy/examples/realm/basic_realm_with_password_policy.yaml
Verify in the relam/authentication left bar of the Keycloak GUI and see;etc the "Passwor dPolicy" tab on the right.

## Checklist:
- [ ] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2021-04-16 08:44 UTC, slaskawi commented
@vmuzikar Could you please have a look at this one?

2021-04-16 10:00 UTC, vmuzikar reviewed
@masoodfaisal Thank you for your contribution!

Could you please fix the linter error and run `make code/gen` to update the CRD? The test error seem to be some random network failure unrelated to this.

Also, please update the commit message. We usually use just the JIRA ID (KEYCLOAK-17607) as the prefix of the message, we don't put the whole URL there.

2021-04-16 10:01 UTC, vmuzikar requested changes
Also, there seem to be some conflicting files.

2021-04-23 07:07 UTC, slaskawi commented
@masoodfaisal Could you please rebase your patch?

2021-04-23 11:32 UTC, masoodfaisal commented
done

2021-04-27 13:59 UTC, slaskawi commented
There's definitely something wrong with this PR. I'm seeing files not belonging to it. Instead of doing a merge, I highly recommend doing a rebase and squashing all changes into a single commit. See https://docs.github.com/en/github/getting-started-with-github/about-git-rebase

2021-04-29 01:10 UTC, masoodfaisal commented
i have done a git reset --hard upstream/master and re-applied my changes.

2021-04-29 06:38 UTC, slaskawi commented
Let's give @vmuzikar a chance to look at it. For me, it's good to go.

2021-04-29 07:06 UTC, vmuzikar approved these changes
@masoodfaisal Thanks for the update, LGTM! There appear to be some suspicious changes in the CRD but I guess we forgot to run `make code/gen` in some other PR.

Btw, for the next time the commit message doesn't need to contain _just_ the JIRA ID but also some actual message, e.g. "KEYCLOAK-17607 Allow Password policy to be defined in the keycloak realm CRD". Thanks!

2021-04-30 09:01 UTC, slaskawi approved these changes

2021-04-30 09:01 UTC, merged

2021-04-30 09:02 UTC, slaskawi commented
Integrated, thanks @masoodfaisal