Updating user mailing list link
keycloak/keycloak-operator pull request #366
Opened 2021-07-19 15:16 UTC by ddowling-act

As per https://lists.jboss.org/archives/list/keycloak-user@lists.jboss.org/thread/HXUE2IPVPB2HCD5TS3V6L7VEYQWI5JRZ/ , the user mailing list has moved to google groups in 2019

## JIRA ID
None, issues do not seem to be enabled on this repository

## Additional Information
This link should be updated to avoid confusion in those looking to ask questions about how to use the operator

## Verification Steps
Documentation change only

## Additional Notes 
I've removed the checklist as this is a minor non-code change. If this is the incorrect thing to do, please let me know

2021-08-17 10:42 UTC, vmuzikar requested changes
@ddowling-act Thank you for your contribution!
Could you please create a JIRA for your changes? Please see the [contribution guide](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md).

2021-11-05 08:40 UTC, ddowling-act commented
Hi @vmuzikar , I shall look into it. Is it an open JIRA system? Do I just sign up for an account?

2021-11-05 09:56 UTC, ddowling-act commented
I have signed up and raised https://issues.redhat.com/browse/KEYCLOAK-19780 for this

2021-11-08 09:40 UTC, stianst approved these changes

2021-11-08 09:41 UTC, stianst commented
@vmuzikar  As this change only affects the readme in the repository there was really no need for a JIRA for this one.

2021-11-08 10:35 UTC, vmuzikar approved these changes
@ddowling-act Thank you, LGTM.

2021-11-08 10:35 UTC, merged