Use networking.k8s.io ingress in cluster role
keycloak/keycloak-operator pull request #393
Opened 2021-11-08 23:08 UTC by hxtmdev

## JIRA ID
- no JIRA ID

## Additional Information
- just deployed 15.0.2 and found that this was probably overlooked in https://github.com/keycloak/keycloak-operator/commit/fd5aeeb3a8dbf672d5751a021b9eea34006afaed#diff-dd2b7f73672812f28eaeefd88568f005bc349b4647e015a36b2789ad29b5221fL66

2022-01-24 13:28 UTC, lutato approved these changes

2022-01-24 13:29 UTC, lutato approved these changes

2022-01-27 09:25 UTC, krzysztof-zych commented
Hi @vmuzikar @stianst
Sorry to bother you, but could you please review this PR and eventually merge it? We need that fix.

Thanks!

2022-01-27 10:17 UTC, vmuzikar requested changes
@hxtmdev Thank you for your contribution! Could you please create a GH Issue for your changes? We don't use JIRA any more, more over KEYCLOAK-18413 is an old and already resolved issue. Please see the [contribution guide](https://github.com/keycloak/keycloak-operator/blob/master/CONTRIBUTING.md).

2022-01-27 11:10 UTC, vmuzikar approved these changes
@hxtmdev LGTM, thank you!

2022-01-27 11:10 UTC, merged