Allow to specify secrets labels and annotations from keycloakclient
keycloak/keycloak-operator pull request #414
Opened 2021-12-08 16:37 UTC by sathieu

## Related GH Issue
Closes #413

## Additional Information

## Verification Steps

I've added unit tests.

Add the steps required to check this change. Following an example.

1. Create a keycloakclient resource with the following spec:

```yaml
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  namespace: keycloak
  name: grafana-oidc-client-secret
  labels:
    app: sso
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: grafana
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    redirectUris:
    - https://grafana.example.org/*
    webOrigins:
    - '+' # redirectUris
    defaultClientScopes:
    - email
    - profile
    # V V V V V V V V V V V here V V V V V V V V V V V
    secretTemplate:
      metadata:
        labels:
          kubed.appscode.com/sync: "kubernetes.io/metadata.name=grafana"
    # Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ here Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ Λ
``` 

2. The keycloak operator will create a secret like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-client-secret
  labels:
    kubed.appscode.com/sync: "kubernetes.io/metadata.name=grafana"
# ...
```

## Checklist:
- [x] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2021-12-08 16:40 UTC, sathieu commented
@vmuzikar @pedroigor @stianst @abstractj Pleas review :pray:!

2022-01-10 14:49 UTC, abstractj commented
@andreaTP @vmuzikar FYI

2022-01-10 17:41 UTC, andreaTP commented
@sathieu the implementation seems to be correct regarding adding the `label`s/`annotation`s; I have no issues with the actual code.

I understand the purpose of this change but it looks a bit involved from a UX perspective, the workflow, as I understand it, looks like:
 - a user creates in one namespace the client-secret
 - the client-secret is propagated across namespaces
 - the deployments are re-started to pick up the new secret?
 
 Now I have some questions:
- what happens if you create multiple different secrets with this annotation? (e.g. with a GitOps pipeline)
- Keycloak deployments are restarted accordingly?
- [most important] can this approach be applied without the additional `kubed` operator dependency?

Thanks a lot in advance for the answer!

2022-01-13 14:38 UTC, andreaTP commented
@sathieu fair answer in this case LGTM

2022-01-13 14:38 UTC, andreaTP approved these changes

2022-01-24 08:20 UTC, sathieu commented
@andreaTP Thanks for approving this PR. Anything I can do to move it forward?

2022-01-24 09:17 UTC, andreaTP commented
Hi @sathieu , I don't have rights to merge, we can ping @vmuzikar to review.

2022-01-24 10:39 UTC, vmuzikar requested changes
@sathieu Thank you for your contribution! The suggestion sounds reasonable to me, changes look good. Could you please add an E2E test for it? I'd like to have this covered not only by a unit test, just in case...

Also, the GH Actions didn't run for some reason. I'll try to close and re-open this PR.

2022-02-02 11:20 UTC, sathieu commented
@vmuzikar I've added some e2e tests. Please unlock the workflows :pray:.

2022-03-25 17:30 UTC, vmuzikar commented on pkg/model/client_secret.go
> +	secret.Labels["app"] = ApplicationName
Something similar also needs to be done here:
https://github.com/keycloak/keycloak-operator/blob/9c9e2b977ff475045ee50f3dd4dcfdc2985388f7/pkg/model/client_secret.go#L44

2022-03-25 17:34 UTC, vmuzikar commented on test/e2e/keycloak_client_test.go
> +			Labels: map[string]string{
We should also test annotations can be set.

2022-04-14 19:41 UTC, tomhuang12 commented
Hoping to have this. @sathieu are you still working on this?

2022-04-15 07:15 UTC, sathieu commented
@tomhuang12 I still need this, but while the unit tests are passing, the e2e tests are failing with "400 Bad request".

I won't work on this soon, feel free to take it.

2022-04-22 06:51 UTC, vmuzikar commented
@sathieu Thank you for your response. I'm going to close this for now. Feel free to reopen or open a new PR when you are able to finish it.

2022-04-22 06:51 UTC, closed without merging