Feature: KeycloakDeploymentSpec.SecurityContext
keycloak/keycloak-operator pull request #460
Opened 2022-01-26 13:59 UTC by Nold360

## Related GH Issue
Closes #458

## Additional Information
Adds PodSecurityContext to Keycloak with default values:
```yaml
runAsNonRoot: true
runAsUser: 1000
runAsGroup: 1000
```

## Checklist:
- [ ] Automated Tests - IDK how to do that, please point me in the right direction
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) - follows if this PR has a chance to get merged

2022-02-04 16:39 UTC, andreaTP commented
Hi @Nold360 , can you add some tests please?
I think that this PR: https://github.com/keycloak/keycloak-operator/pull/414/files is small enough and shows how to add tests in the relevant sections.

2022-02-05 10:05 UTC, Nold360 commented
I think i figured out this unit test thing :D

2022-02-07 08:52 UTC, andreaTP commented
LGTM, cc. @vmuzikar

2022-02-07 08:52 UTC, andreaTP approved these changes

2022-02-07 18:16 UTC, Nold360 commented
Fixed the commit message

2022-03-25 17:39 UTC, vmuzikar commented
Closing and re-opening to fix the CI.

2022-03-25 17:47 UTC, vmuzikar requested changes
@Nold360 Thank you for your contribution! Added a few comments.

2022-03-25 17:47 UTC, vmuzikar commented on pkg/model/keycloak_deployment.go
> +	}
This is potentionally a breaking change, we weren't setting any defaults before. Could you please remove it?

2022-04-20 13:51 UTC, vmuzikar commented
@Nold360 Just wanted to ask if this is still something you'd like to work on.

2022-04-29 15:25 UTC, vmuzikar commented
@Nold360 Closing this for now. Feel free to reopen!

2022-04-29 15:25 UTC, closed without merging