#500 Add annotation to podSpec
keycloak/keycloak-operator pull request #501
Opened 2022-03-09 14:07 UTC by bovigny

Signed-off-by: bovigny <bovignyc@gmail.com>

## Related GH Issue
Closes #500 

## Additional Information
Add annotations to podSpec

## Checklist:
- [x] Automated Tests
- [ ] [Documentation](https://github.com/keycloak/keycloak-documentation) changes if necessary
- [ ] (If required) Discussed on [Keycloak DEV](https://groups.google.com/forum/#!forum/keycloak-dev)

2022-04-11 09:28 UTC, Stefanqn commented
Linting fails.

2022-04-11 16:14 UTC, vmuzikar requested changes
@bovigny Thank you for your contribution! Added a few comments.

2022-04-11 16:14 UTC, vmuzikar commented on pkg/model/constants.go
> +var PodAnnotations = map[string]string{}
We don't need this (unlike for Labels).

2022-04-20 09:02 UTC, vmuzikar commented
@bovigny Hi, just wanted to ask if this is still something you want to work on. We now have a very similar PR #531. Maybe we can close this one in favor of #531.

2022-04-20 13:39 UTC, vmuzikar commented
I'm closing this as #531 was merged.

2022-04-20 13:39 UTC, closed without merging