GH Action to release the container image
keycloak/keycloak-operator pull request #504
Opened 2022-03-11 12:50 UTC by andreaTP

## Related GH Issue

Resolves #503 

## Additional Information

Tested publishing the image to my private docker.io account:
https://hub.docker.com/repository/docker/andreatp/keycloak-operator

2022-03-11 17:01 UTC, vmuzikar requested changes
@andreaTP Can't access the test build in your private repo but I trust you it went ok. 😜

2022-03-11 17:01 UTC, vmuzikar commented on .github/workflows/release-container.yml
> +        uses: docker/setup-qemu-action@v1
We don't need QEMU.

2022-03-11 17:03 UTC, vmuzikar commented
@andreaTP I presume you did try deploying the operator using the image built by this workflow, right?

2022-03-11 18:17 UTC, andreaTP commented on .github/workflows/release-container.yml
> +          platforms: linux/amd64,linux/arm64
removed

2022-03-11 18:18 UTC, andreaTP commented on .github/workflows/release-container.yml
> +        uses: docker/setup-qemu-action@v1
removed

2022-03-11 18:18 UTC, andreaTP commented
> @andreaTP I presume you did try deploying the operator using the image built by this workflow, right?

yup, checked 👍

2022-03-14 08:07 UTC, vmuzikar requested changes
I'm probably doing something wrong but I'm not successful at testing it. Steps I did:
1. `make cluster/prepare`.
2. Update [`operator.yaml`](https://github.com/keycloak/keycloak-operator/blob/main/deploy/operator.yaml) with your image: `andreatp/keycloak-operator:6.7.8`.
3. `kubectl apply -f operator.yaml -n keycloak`

Getting the following error:
```
          Error response from daemon: OCI runtime create failed: container_linux.go:380:
          starting container process caused: exec: "keycloak-operator": executable
          file not found in $PATH: unknown
```

2022-03-14 09:22 UTC, andreaTP commented
@vmuzikar `6.7.8` is the new operator, tested with `2.3.4` (still running):
![Screenshot 2022-03-14 at 09 21 06](https://user-images.githubusercontent.com/5792097/158142695-bd27cec7-6431-43b9-b6c7-14085c8d17ca.png)

2022-03-14 09:51 UTC, vmuzikar commented
@andreaTP Ok then. I presumed all tags are the old operator, just saw arm at the 2.3.4 build so assumed it's older.

2022-03-14 09:52 UTC, vmuzikar approved these changes
LGTM, but I'd like @stianst to check this too before merging.

2022-03-14 10:26 UTC, andreaTP commented on .github/workflows/release-container.yml
> +          tags: ${{ steps.meta.outputs.tags }}
done at line 25:
https://github.com/keycloak/keycloak-operator/pull/504/files#diff-69a4610cce35bf32d579cc8d14aa59de81d80d23f0269d80861bceb81f57b176R25

2022-03-14 10:37 UTC, andreaTP commented on .github/workflows/release-container.yml
> +          tags: ${{ steps.meta.outputs.tags }}
What about `latest` ?

2022-03-14 10:57 UTC, andreaTP commented on .github/workflows/release-container.yml
> +          tags: ${{ steps.meta.outputs.tags }}
Pretty original encoding, but done:
![Screenshot 2022-03-14 at 10 54 53](https://user-images.githubusercontent.com/5792097/158158749-3d42ad65-2b3b-46f6-8c1b-cb435a91ad7f.png)

2022-03-14 10:58 UTC, vmuzikar approved these changes
LGTM, but let's wait for @stianst on this one.

2022-03-15 09:43 UTC, stianst commented on .github/workflows/release-container.yml
> +          tags: ${{ steps.meta.outputs.tags }}
Take a look at https://github.com/keycloak/keycloak-containers/pull/385/files#diff-69a4610cce35bf32d579cc8d14aa59de81d80d23f0269d80861bceb81f57b176R36-R38

That just uses the raw types to create "18.0.0-legacy" and "legacy" tags. With the semver it also would tag as `latest` and potentially overwriting the new operator.

2022-03-15 10:08 UTC, andreaTP commented on .github/workflows/release-container.yml
> +          tags: ${{ steps.meta.outputs.tags }}
@stianst if you really prefer the encoding linked I can change this, but, here `latest` is explicitly disabled here:
https://github.com/keycloak/keycloak-operator/pull/504/files#diff-69a4610cce35bf32d579cc8d14aa59de81d80d23f0269d80861bceb81f57b176R27

and I tested that's a correct encoding and it doesn't overwrite `latest`

2022-03-16 08:39 UTC, stianst approved these changes

2022-03-16 08:39 UTC, merged